서버 데이터 수정 및 추가
dev-answer/dev-answer pull request #31
Opened 2021-07-15 14:05 UTC by gyim1345

## Why

-  https://github.com/dev-answer/dev-answer/issues/30

## What

파일 리더로 자동화 시도

## Notes

데이터 타이틀 및 레벨 추가 수정 필요

2021-07-18 14:54 UTC, Woomin-Jeon commented on server/src/db/questionCategory.json
>  ]
EOFFFFF

2021-07-18 16:39 UTC, daadaadaah requested changes
수고하셨습니다~ㅎㅎ

2021-07-18 16:39 UTC, daadaadaah approved these changes
수고하셨습니다~ㅎㅎ

2021-07-22 12:38 UTC, gyim1345 commented on server/src/db/questionCategory.json
>  ]
EOFFF 가 무슨 뜻이죠?

2021-07-22 12:56 UTC, Woomin-Jeon commented on server/src/db/questionCategory.json
>  ]
End of File이요 ㅋㅋ 파일 마지막줄 개행이 안돼있어서요!

2021-07-22 12:59 UTC, gyim1345 commented on server/src/db/questionCategory.json
>  ]
오 그런게 있었군요! 배워갑니다!

2021-07-24 07:07 UTC, passwd10 approved these changes
고생하셨습니다!

2021-08-20 15:50 UTC, gyim1345 commented
mongodb 사용 예정으로 그냥 닫습니다.

2021-08-20 15:50 UTC, closed without merging